#! /usr/bin/env sh

WORKDIR=$(pwd)

setup(){
    cd "$1"
    basename `pwd` > README.md
    echo "========================" >> README.md
    echo "" >> README.md
    find . -maxdepth 1 -type d -exec bash -c "echo -n '- ' stat -c %y {} | cut -d ' ' -f 1 | tr -d '\n'; echo ' '[{}]\({}\) | tr -d './' " \; | grep -v '\[\]\(\)' >> README.md
    cd "$WORKDIR"
}

setup

for file in `find dists pool -type d`; do
    setup $file
done